# Generated by Django 4.2.17 on 2025-01-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedpdf",
            name="processing_progress",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
